### ISSUE TITLE
Login fails: "Data must be aligned to block boundary in ECB mode"

### ISSUE THREAD

**Issue by janedenone** [wandera/1password-client#12] opened 2021-04-05 11:22 UTC
Hi, logging into my 1password account fails with the ValueError message above:

`from onepassword import OnePassword
op = OnePassword()
1Password master password: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/onepassword/client.py", line 60, in __init__
    self.encrypted_master_password, self.session_key = self.signin_wrapper(master_password=password)
  File "/opt/homebrew/lib/python3.9/site-packages/onepassword/client.py", line 179, in signin_wrapper
    encrypted_str = encrypt.encode(password)
  File "/opt/homebrew/lib/python3.9/site-packages/onepassword/utils.py", line 173, in encode
    return base64.b64encode(self.cipher.encrypt(input_str.rjust(32)))
  File "/opt/homebrew/lib/python3.9/site-packages/Crypto/Cipher/_mode_ecb.py", line 141, in encrypt
    raise ValueError("Data must be aligned to block boundary in ECB mode")
ValueError: Data must be aligned to block boundary in ECB mode`

Python 3.9.2, op 1.8.0, 1password-client 0.3.0

Best regards, Jan

**Comment by dtpryce** [comment] 2021-04-08 16:08
I will test this with a docker image ... not sure I have ever seen this bug, trying to replicate now.

**Comment by dtpryce** [comment] 2021-04-08 16:16
Haven't got the same issue but something isn't right in the first use or sign in steps ... will investigate further

**Comment by dtpryce** [comment] 2021-04-09 11:07
I was not able to reproduce your issue sadly ... might be a kernel issue however without more detail / investigation not sure what to do. 

For now we are about to release a new version of the client that should ensure you can sign in and use the newer and fixed version (1.8.0) of the cli and further updates we can test before releasing a new client instead of the auto-updates that were causing issues.

**Comment by dtpryce** [comment] 2021-04-09 15:03
@janedenone could you please try to use the newest version of the library (0.4.1), if you need any help with usage please create a new issue. 

Ok for me to close this one?

**Comment by janedenone** [comment] 2021-04-10 10:21
Thanks for looking into this. I just updated to 0.4.1, but the problem persists. This issue can be closed regardless, I will use pyonepassword for now.

Thanks again, Jan

**Comment by dtpryce** [comment] 2021-04-10 15:00
Fair enough ... Do try 0.4.3 just in case, I am intrigued as to how it's happening since I can't reproduce it so any more details you can share on your system and setup would be helpful.

**Comment by dtpryce** [comment] 2021-04-10 15:03
Ooo ok I've read up more on Crypto ... Can your tell me the length of your master password? Might be the padding or unpadding to encrypt and decrypt

**Comment by dtpryce** [comment] 2021-04-10 16:29
I am guessing longer than 32 characters :D ... ok I am digging now!

**Comment by dtpryce** [comment] 2021-04-10 16:46
@janedenone was able to reproduce and now fixing :D no need to change to pyonepassword ;)

**Closed** 2021-04-10 17:00 UTC
Labels: question, ready to close

**Comment by dtpryce** [comment] 2021-04-10 17:09
Please install version `0.4.4` (just released) and test it out 🤞🏼 your problem does not persist any longer 🤞🏼

**Comment by janedenone** [comment] 2021-04-10 19:54
> Please install version `0.4.4` (just released) and test it out 🤞🏼 your problem does not persist any longer 🤞🏼 @janedenone

Thank you! I installed 0.4.4 and was able to login to 1Password, although I get a warning message.

```/bin/sh: base32: command not found```

Have a great weekend!

**Comment by dtpryce** [comment] 2021-04-10 21:11
Did it stop the client working? i.e. can you run the basic example in the README and get your private vault items back?

**Comment by dtpryce** [comment] 2021-04-10 22:16
What distro of Linux are you using?

**Comment by janedenone** [comment] 2021-04-11 04:02
> Did it stop the client working? i.e. can you run the basic example in the README and get your private vault items back?

Unfortunately, the basic example provides a login prompt for 1Password, but does not display my vaults/items. 

> What distro of Linux are you using?

macOS 11 (BigSur) on a M1 MacBook Pro. The ARM architecture creates another issue when installing version 0.4.4 (s. attached installation log).
[install.log](https://github.com/wandera/1password-client/files/6291167/install.log)

**Comment by dtpryce** [comment] 2021-04-11 09:23
Oh now I understand the issue ... The new M1 machines! Haven't got hold of one yet but I know from some of our developers they aren't handling a lot of software well yet. I will dig into the issue a little but fear this won't be the only time you get issues like this.

**Comment by dtpryce** [comment] 2021-04-11 09:29
I think your issue stems from homebrew not officially supporting the ARM M1 architecture yet ... Maybe this will help https://github.com/mikelxc/Workarounds-for-ARM-mac 

?? Until I am able to help my hands on one might be hard to help here though :(

**Comment by dtpryce** [comment] 2021-04-11 09:51
And then installing GNU coreutils (the missing base64 should be in there) could be the fix

**Comment by dtpryce** [comment] 2021-04-11 21:26
Also found a lot of issues with M1 and pycryptodome ... try downgrading to python 3.9.1 or 3.8 and retrying. https://github.com/Legrandin/pycryptodome/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+M1

**Comment by dtpryce** [comment] 2021-04-13 08:26
@janedenone can you tell me what you get if you run the following in python `import platform; print(platform.machine()); print(platform.system())` please?

**Comment by janedenone** [comment] 2021-04-13 09:31
Sure, I get:

arm64
Darwin

I was able to install several brew formulae (many of which are marked as ARM native) and Python packages on my machine.
