### ISSUE TITLE
How do I start a session?

### ISSUE THREAD

**Issue by iainelder** [wandera/1password-client#30] opened 2021-07-06 18:16 UTC
I can't get past the first command in the sample code.

In bash set up a REPL like this:

```bash
pip install 1password
pip install ipython
ipython
```

Paste this into IPython:

```python
from onepassword import OnePassword
import json

op = OnePassword()
```

Follow the dialog like this:

```text
Please input your email address used for 1Password account: ...@hotmail.co.uk
Is your 1Password domain: hotmail.1password.com (y/n)? n
Please input your 1Password domain in the format <something>.1password.com: my.1password.com
Is your 1Password account name: hotmail (y/n)? n
Please input your 1Password account name e.g. wandera from wandera.1password.com: my
Please input your 1Password secret key: 
Please input your 1Password master password: 
```

The last input hangs for a while before finally producing a timeout error. Full trace below.

An extra line was added to my .bashrc:

```
export OP_DEVICE="pq..."
```

How do I skip all the dialog and just sign in using the config that op already has?

How do I avoid modifying my .bashrc?

When op is already configured, starting a session simple as `op signin` and remembering the session ID value for subsequent commands.

```text
---------------------------------------------------------------------------
TIMEOUT                                   Traceback (most recent call last)
<ipython-input-3-cfd2635b5c0d> in <module>
      2 import json
      3 
----> 4 op = OnePassword()

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/onepassword/client.py in __init__(self, account, domain, email, secret, password)
     42                                                                                    master_password=password)
     43         else:
---> 44             self.first_use()
     45 
     46     @staticmethod

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/onepassword/client.py in first_use(self)
     74             account = input("Please input your 1Password account name e.g. wandera from wandera.1password.com: ")
     75         secret_key = getpass("Please input your 1Password secret key: ")
---> 76         self.signin_wrapper(account, signin_domain, email_address, secret_key)
     77 
     78     def signin_wrapper(self, account=None, domain=None, email=None, secret_key=None, master_password=None):

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/onepassword/client.py in signin_wrapper(self, account, domain, email, secret_key, master_password)
    101         """
    102 
--> 103         password, session_key, domain, account, bp = self._signin(account, domain, email, secret_key, master_password)
    104         tries = 1
    105         while tries < 3:

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/onepassword/client.py in _signin(account, domain, email, secret_key, master_password)
    170                     raise ValueError("First signin failed or not executed.")
    171             op_command = "op signin {} --raw".format(account)
--> 172         sess_key = _spawn_signin(op_command, master_password)
    173         return master_password, sess_key, domain, account, bp
    174 

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/onepassword/utils.py in _spawn_signin(command, m_password)
     64     if command != "":
     65         child = pexpect.spawn(command)
---> 66         child.expect([master_password_regex, pexpect.EOF])
     67         if child.isalive():
     68             try:

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/pexpect/spawnbase.py in expect(self, pattern, timeout, searchwindowsize, async_, **kw)
    341 
    342         compiled_pattern_list = self.compile_pattern_list(pattern)
--> 343         return self.expect_list(compiled_pattern_list,
    344                 timeout, searchwindowsize, async_)
    345 

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/pexpect/spawnbase.py in expect_list(self, pattern_list, timeout, searchwindowsize, async_, **kw)
    370             return expect_async(exp, timeout)
    371         else:
--> 372             return exp.expect_loop(timeout)
    373 
    374     def expect_exact(self, pattern_list, timeout=-1, searchwindowsize=-1,

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/pexpect/expect.py in expect_loop(self, timeout)
    179             return self.eof(e)
    180         except TIMEOUT as e:
--> 181             return self.timeout(e)
    182         except:
    183             self.errored()

~/.local/share/virtualenvs/e8ec509671f70de/lib/python3.8/site-packages/pexpect/expect.py in timeout(self, err)
    142             exc = TIMEOUT(msg)
    143             exc.__cause__ = None    # in Python 3.x we can use "raise exc from None"
--> 144             raise exc
    145 
    146     def errored(self):

TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f2db403f790>
command: /usr/local/bin/op
args: ['/usr/local/bin/op', 'signin', 'my.1password.com', '...@hotmail.co.uk', 'A3-...', '--raw', '--shorthand', 'my']
buffer (last 100 chars): b'Enter the password for ...@hotmail.co.uk at my.1password.com: '
before (last 100 chars): b'Enter the password for ...@hotmail.co.uk at my.1password.com: '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 45987
child_fd: 14
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'Enter the password for [a-zA-Z0-9._%+-]+\\@[a-zA-Z0-9-]+\\.[a-zA-z]{2,4} at [a-zA-Z0-9-.]+\\.1password+\\.[a-zA-z]{2,4}')
    1: EOF

```

**Comment by iainelder** [comment] 2021-07-06 18:19
Apart from being inconvenient, this also seems to risk credential leakage.

I had to redact the secret key from the error output before posting it here.

The op command may support inputting sensitive data as command-line arguments, but it doesn't make it a good idea.

**Comment by dtpryce** [comment] 2021-07-11 10:39
We encrypt your password within the kernel so the risk of a leak is very small indeed. We could extend this to secret key but that is only asked for once in reality. 

Other than that you have to interact with the bash profile to make the client usable since that's now op knows you have logged in before and python os.environ is ephemeral. 

I will take what you have here and try to reproduce again and then fulfill your use case though.

**Comment by dtpryce** [comment] 2021-07-11 10:43
How have you already configured op? Because for that you need to have set the env variables and if that is done then our client will move straight to the password asking phase. 

If you have an account configured in op already then you can feed that account like so 

`op = OnePassword(account="name of account")` 

And then it should just ask for your password 🤞

**Comment by dtpryce** [comment] 2021-07-11 10:44
The error you have there is around the regex we use and I think I can fix it but want to get your use case sorted also

**Comment by dtpryce** [comment] 2021-07-13 08:08
@iainelder have you considered trying using Secrets Automation? 

Requires a docker or k8s environment to then leverage the 1Password API but might suit your use case more? 

https://1password.com/secrets

**Comment by iainelder** [comment] 2021-07-13 14:35
> Other than that you have to interact with the bash profile to make the client usable since that's now op knows you have logged in before and python os.environ is ephemeral.

I have nothing in my bash profile for the op CLI.

> How have you already configured op?

I don't remember exactly, but I expect I just ran the example signin command from the [Getting Started](https://support.1password.com/command-line-getting-started/) documentation.

```
op signin example.1password.com wendy_appleseed@example.com
```

On Ubuntu it appears to save the config in a folder called ~/.config/1Password.

There's a SQLite database in there called 1password.sqlite with an accounts table that contains a row that contains my user email, my secret key, and everthing else the op command needs to recognise me.

All that allows me subsequently to simply type `op signin`, then type my master password, and then get a session token in return.

Because of that I'm not expecting to have to share any of that info again with a Python client if it is just driving the op CLI.

To work with the op CLI directly you can save the session token as an environment variable, or you can pass it to each command using the `--session` parameter.

Editing ~/.bashrc is a convenient way to make the environment variable persist across shell sessions, but I don't expect any Python module to be be modifying it for me automatically. I keep my .bashrc in version control so I prefer not to set ephemeral session tokens or anything else there.

Ideally I'd like the Python client to just use whatever credentials have already been configured out-of-band. How well does that sit with your existing use cases?

> have you considered trying using Secrets Automation?

I saw it and thought it was either too complicated (kubernetes is overkill for this) or too "enterprise" (as in not compatible with personal 1Password accounts).

But I see it has an official Python SDK and I don't see anything restricting it to business accounts. If the Docker part is easy to set up, then it might be a solution more-or-less tidy than CLI scraping :-)

**Comment by iainelder** [comment] 2021-07-13 14:42
Just reread this part, I'll try it now!

> If you have an account configured in op already then you can feed that account like so
> 
>     op = OnePassword(account="name of account")

**Comment by iainelder** [comment] 2021-07-13 14:49
I get the same behavior when I call it like this:

```
op = OnePassword(account="my.1password.com")
```

I don't know if the account name is set correctly, but if it weren't I would expect "No such account" or something like that.

> On Ubuntu it appears to save the config in a folder called ~/.config/1Password.

This might actually be config for the GUI version. If the CLI doesn't use this then I don't know where the CLI stores its config!

**Comment by dtpryce** [comment] 2021-07-13 14:54
No account is the name you have set and that should be saved in your `op` config / cache. 

The cli leverages what is in `~/.config/op` directory and we leverage the cli basically. The only things the client needs is the bash profile to persist those env variables (which the cli also asks users to do using eval) and we do so securely and safely now with no damage to existing profiles. 

If you want that much control over both the cli and bash environment my next question would be why do you need the python client at all? :P 

Also maybe a call would help here and might be cool to meet since you clearly have an interest in our client :D

**Comment by dtpryce** [comment] 2021-07-13 14:56
> No account is the name you have set and that should be saved in your `op` config / cache.

In my use case I would input:
- email = david.pryce@wandera.com
- domain = wandera (since we login with wandera.1password.com)
- account = wandera (but this can be anything I want to name it, is entirely up to you and is just to ensure parity with op and our session variable naming)

**Comment by dtpryce** [comment] 2021-07-13 15:33
I also just tested in an ubuntu docker image and all works as expected with my login and using 2FA also.

**Comment by dtpryce** [comment] 2021-07-13 16:08
> Because of that I'm not expecting to have to share any of that info again with a Python client if it is just driving the op CLI.

Correct on second use of the client you wouldn't have to use that _or_ you can use the account value like I suggested to skip the first_use method in the client and utilise the cli setup, if that has been done already.

**Comment by dtpryce** [comment] 2021-07-13 16:09
> Editing ~/.bashrc is a convenient way to make the environment variable persist across shell sessions, but I don't expect any Python module to be be modifying it for me automatically. I keep my .bashrc in version control so I prefer not to set ephemeral session tokens or anything else there.

The session key only works for 15 minutes anyhow so it's really just for those that are doing something programatically or using notebooks for example where you may not want to always supply a password all the time.

**Comment by iainelder** [comment] 2021-07-19 10:54
> If you want that much control over both the cli and bash environment my next question would be why do you need the python client at all? :P

Because I'm using OnePassword to store credentials as part of a script controlled by Python. My research led me to believe that the only way to programmatically access OnePassword was with the CLI, so I could drive it using Expect or use any library (like this one) that does it for me.

> Also maybe a call would help here and might be cool to meet since you clearly have an interest in our client :D

Sorry I've been out of touch last week. It's just a hobby project, nothing urgent, and now I'll be busy with other things for the next month or so!

To keep this ticket focused on the initial reported problem: I suppose if that gets resolved then we can close it.

On my own time I can investigate the secrets automation API to see if it suits my use case and is not too much of an extra dependency. It seems there is no way to avoid an external process, whether it be the op CLI or some Docker container...

**Comment by dtpryce** [comment] 2021-08-29 11:49
I understand ... ok I will try and investigate at some point in the future but not been able to reproduce or seen in others machines. Will try one more time soon and then might have to close this ticket, but feel free to add any more details here when you have a chance!

**Comment by iainelder** [comment] 2021-08-31 07:28
Hi, yes, feel free to close the ticket.

In the meantime I found another client that is a better fit for my needs: https://github.com/zcutlip/pyonepassword

It better fits my mental model of how I want the Python library to work.

**Closed** 2021-11-24 10:32 UTC
